services:
  client:
    image: client
    ports: 
      # - 8080:3000 // hot reload doesn't work
      - 3000:3000
    command: npm run start
    volumes: 
      - ./client/src/:/app/src/
    env_file:
      - ./client/.env
  server:
    build: ./server
    ports: 
      - 5050:5000
    command: npm run dev
    volumes: 
      - ./server/src/:/app/src/
    env_file:
      - ./server/.env
  mongodb:
    image: mongo
    volumes: 
      - ./data:/data/db